### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by abcdan** [daanbreur/stream-overlay#3]
I was scrolling through random projects on Github and came across yours, not sure if you are Dutch or not based on your name so I'll just continue in English.

First of all, the project looks amazing! I'd just suggest using a database like [Chainson](https://github.com/abcdan/chainson), Enmap, etc. instead of a plain `json` file!

Cheers 🍻

**Comment by daanbreur** [comment]
Thanks for your suggestion! 👍 And for liking the project 💜

But we (the chat and I) specifically chose to use a `json` file to make it more vanilla.
I think it may be time to rework the project a tiny bit to make it even better.

**Comment by abcdan** [comment]
Yeah! That's why I suggested one of the projects I created. It's a database that uses a JSON file underlying so you can easily move/edit data without having to start your application yet it's easy to use with `.set()` `.get()` :)

**Comment by daanbreur** [comment]
That sounds awesome, just like what we have but different? Can you have nested `objects/arrays` tho?

**Comment by daanbreur** [comment]
@abcdan We eventually chose to go with MongoDB, this is new for us and we like learning on the streams
